import type { Position } from './types';

export const openPositions: Position[] = [
  {
    id: 'marketing-strategist',
    title: 'Marketing Strategist',
    subtitle: '(Part-Time or Contract)',
    description: [
      'This role is ideal for someone who thrives on both creative storytelling and strategic systems. As a Marketing Strategist, you’ll collaborate directly with our founder and clients to design marketing frameworks that drive visibility, demand, and results, without resorting to burnout tactics or noise.',
      'You’ll be responsible for building full-funnel strategies, positioning offers, and creating content plans that support long-term growth, not just short-term clicks. You’ll also support in refining client messaging, auditing marketing assets, and occasionally jumping into client sessions or Loom feedback rounds to help guide execution.',
    ],
    fitSkills: [
      'Love helping people simplify their message and amplify their reach',
      'Have experience with service-based businesses or creator brands',
      'Understand how content, email, and funnels work together',
      'Can speak both strategy and execution, and know when each is needed',
      'Know how to guide, not just tell',
      'Enjoy contributing to something that’s growing — and growing fast',
    ],
    niceToHave: [
      'Experience with tools like ConvertKit, Notion, and Airtable',
      'Past work with small brands, coaches, or freelancers',
      'Familiarity with storytelling frameworks or digital copywriting',
    ],
    estimatedTime: '8–15 hours/week',
    compensation: 'Project-based or retainer, depending on fit',
    location: 'Remote',
    responsibilities: [
      'Auditing and refining existing brand messaging',
      'Mapping full-funnel content strategies (organic & email)',
      'Developing audience profiles and content themes',
      'Advising on conversion-optimized offers and CTAs',
      'Collaborating with the founder on positioning pivots or launches',
      'Providing insights and analysis based on campaign performance',
      'Translating business goals into actionable marketing workflows',
    ],
    quote: 'Hold the thread.  Keep the flow.  Deliver the experience.',
  },
  {
    id: 'operations-systems-consultant',
    title: 'Operations & Systems Consultant',
    description: [
      'As an Operations & Systems Consultant, you’ll work behind the scenes to help solo founders streamline their workflows, automate repetitive tasks, and build the systems they need to support growth without the overwhelm. You’ll take high-level goals and transform them into transparent, well-documented processes that clients can rely on.',
      'This is a blend of systems thinking, operational mapping, and client collaboration. You’re not just solving problems — you’re creating ease, structure, and the ability to scale.',
    ],
    quote: 'Turn chaos into clarity for growing personal brands.',
    fitSkills: [
      'Think in systems and enjoy turning complexity into order',
      'Can translate messy notes into structured workflows',
      'Have experience working with solo founders, creators, or consultants',
      'Are tech-comfortable and quick to learn new tools',
      'Enjoy helping others move faster, with less friction',
    ],
    niceToHave: [
      'Experience with automation tools (Zapier, Make, etc.)',
      'Familiarity with service-based business models',
      'Ability to create simple Loom walkthroughs for clients',
    ],
    estimatedTime: '10–20 hours/months',
    compensation: 'Retainer or hourly',
    location: 'Remote (Flexible hours)',
    responsibilities: [
      'Auditing and optimizing internal client workflows',
      'Mapping out scalable SOPs, automations, and CRM processes',
      'Recommending and implementing tools (e.g., Airtable, Notion, Zapier)',
      'Assisting clients with backend setup (booking systems, pipelines, forms)',
      'Creating dashboards and visibility tools for progress tracking',
      'Collaborating with the team to ensure systems align with the strategy',
    ],
  },
  {
    id: 'client-success-lead',
    title: 'Client Success Lead',
    quote: 'Hold the thread. Keep the flow. Deliver the experience.',
    description: [
      'This role focuses on client experience and operational oversight. As our Client Success Lead, you’ll be the connective tissue between our clients, consultants, and internal projects. You’ll ensure that everyone has what they need, deadlines remain visible, and communication stays clear and respectful.',
      'You’re not just managing logistics — you’re upholding a standard of excellence and care. You’ll anticipate needs, handle details, and maintain momentum across multiple client journeys.',
    ],
    fitSkills: [
      'Love creating structure and clarity in moving environments',
      'Are highly organized and proactive with follow-through',
      'Communicate with warmth, precision, and professionalism',
      'Enjoy being in a hybrid role between people, processes, and problem-solving',
      'Can manage multiple client journeys without dropping the thread',
    ],
    niceToHave: [
      'Experience with CRMs, Notion, or task management tools',
      'Familiarity with coaching, consulting, or service-based businesses',
      'A knack for writing clear, friendly emails and updates',
    ],
    estimatedTime: '10–12 hours/week',
    compensation: 'Retainer',
    location: 'Remote',
    responsibilities: [
      'Managing project timelines, session schedules, and deliverables',
      'Acting as the first point of contact for client communication',
      'Gathering session notes, resources, and client inputs',
      'Tracking progress and surfacing any red flags',
      'Supporting the founder with light admin and project coordination',
      'Ensuring a smooth and professional experience from onboarding to offboarding',
    ],
  },
];
