import type { Metadata } from 'next';
import localFont from 'next/font/local';

import { cn } from '@/shared/lib/utils/styles';

import './globals.css';

const suisseIntl = localFont({
  src: [
    {
      path: '../../public/fonts/suisse-intl/light.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../../public/fonts/suisse-intl/regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/suisse-intl/medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../public/fonts/suisse-intl/bold.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(suisseIntl.className, 'antialiased')}>
        {children}
      </body>
    </html>
  );
}
